FROM node:lts-alpine3.17 as build

EXPOSE 3000

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install --force 
#Im forcing the install for the svelte-confetti. If there are any potential bugs, I will revert back and not use the confetti

COPY . .

RUN astro build

FROM nginx:latest as server


RUN sed -i "s/80/3000/g" /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]